// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v3.9.0
// source: proto/hop_tunnel.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HopPacket struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HopPacket) Reset() {
	*x = HopPacket{}
	mi := &file_proto_hop_tunnel_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HopPacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HopPacket) ProtoMessage() {}

func (x *HopPacket) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hop_tunnel_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HopPacket.ProtoReflect.Descriptor instead.
func (*HopPacket) Descriptor() ([]byte, []int) {
	return file_proto_hop_tunnel_proto_rawDescGZIP(), []int{0}
}

func (x *HopPacket) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// 注册包
type RegisterPacket struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Host          string                 `protobuf:"bytes,3,opt,name=host,proto3" json:"host,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterPacket) Reset() {
	*x = RegisterPacket{}
	mi := &file_proto_hop_tunnel_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterPacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterPacket) ProtoMessage() {}

func (x *RegisterPacket) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hop_tunnel_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterPacket.ProtoReflect.Descriptor instead.
func (*RegisterPacket) Descriptor() ([]byte, []int) {
	return file_proto_hop_tunnel_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterPacket) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterPacket) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *RegisterPacket) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

var File_proto_hop_tunnel_proto protoreflect.FileDescriptor

var file_proto_hop_tunnel_proto_rawDesc = string([]byte{
	0x0a, 0x16, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x68, 0x6f, 0x70, 0x5f, 0x74, 0x75, 0x6e, 0x6e,
	0x65, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x1f, 0x0a, 0x09,
	0x48, 0x6f, 0x70, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x52, 0x0a,
	0x0e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a,
	0x04, 0x68, 0x6f, 0x73, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x6f, 0x73,
	0x74, 0x32, 0x37, 0x0a, 0x09, 0x48, 0x6f, 0x70, 0x54, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x12, 0x2a,
	0x0a, 0x06, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x12, 0x0d, 0x2e, 0x70, 0x62, 0x2e, 0x48, 0x6f,
	0x70, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x1a, 0x0d, 0x2e, 0x70, 0x62, 0x2e, 0x48, 0x6f, 0x70,
	0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x28, 0x01, 0x30, 0x01, 0x42, 0x05, 0x5a, 0x03, 0x2f, 0x70,
	0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_proto_hop_tunnel_proto_rawDescOnce sync.Once
	file_proto_hop_tunnel_proto_rawDescData []byte
)

func file_proto_hop_tunnel_proto_rawDescGZIP() []byte {
	file_proto_hop_tunnel_proto_rawDescOnce.Do(func() {
		file_proto_hop_tunnel_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_hop_tunnel_proto_rawDesc), len(file_proto_hop_tunnel_proto_rawDesc)))
	})
	return file_proto_hop_tunnel_proto_rawDescData
}

var file_proto_hop_tunnel_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_hop_tunnel_proto_goTypes = []any{
	(*HopPacket)(nil),      // 0: pb.HopPacket
	(*RegisterPacket)(nil), // 1: pb.RegisterPacket
}
var file_proto_hop_tunnel_proto_depIdxs = []int32{
	0, // 0: pb.HopTunnel.Stream:input_type -> pb.HopPacket
	0, // 1: pb.HopTunnel.Stream:output_type -> pb.HopPacket
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_hop_tunnel_proto_init() }
func file_proto_hop_tunnel_proto_init() {
	if File_proto_hop_tunnel_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_hop_tunnel_proto_rawDesc), len(file_proto_hop_tunnel_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_hop_tunnel_proto_goTypes,
		DependencyIndexes: file_proto_hop_tunnel_proto_depIdxs,
		MessageInfos:      file_proto_hop_tunnel_proto_msgTypes,
	}.Build()
	File_proto_hop_tunnel_proto = out.File
	file_proto_hop_tunnel_proto_goTypes = nil
	file_proto_hop_tunnel_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// HopTunnelClient is the client API for HopTunnel service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type HopTunnelClient interface {
	Stream(ctx context.Context, opts ...grpc.CallOption) (HopTunnel_StreamClient, error)
}

type hopTunnelClient struct {
	cc grpc.ClientConnInterface
}

func NewHopTunnelClient(cc grpc.ClientConnInterface) HopTunnelClient {
	return &hopTunnelClient{cc}
}

func (c *hopTunnelClient) Stream(ctx context.Context, opts ...grpc.CallOption) (HopTunnel_StreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &_HopTunnel_serviceDesc.Streams[0], "/pb.HopTunnel/Stream", opts...)
	if err != nil {
		return nil, err
	}
	x := &hopTunnelStreamClient{stream}
	return x, nil
}

type HopTunnel_StreamClient interface {
	Send(*HopPacket) error
	Recv() (*HopPacket, error)
	grpc.ClientStream
}

type hopTunnelStreamClient struct {
	grpc.ClientStream
}

func (x *hopTunnelStreamClient) Send(m *HopPacket) error {
	return x.ClientStream.SendMsg(m)
}

func (x *hopTunnelStreamClient) Recv() (*HopPacket, error) {
	m := new(HopPacket)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// HopTunnelServer is the server API for HopTunnel service.
type HopTunnelServer interface {
	Stream(HopTunnel_StreamServer) error
}

// UnimplementedHopTunnelServer can be embedded to have forward compatible implementations.
type UnimplementedHopTunnelServer struct {
}

func (*UnimplementedHopTunnelServer) Stream(HopTunnel_StreamServer) error {
	return status.Errorf(codes.Unimplemented, "method Stream not implemented")
}

func RegisterHopTunnelServer(s *grpc.Server, srv HopTunnelServer) {
	s.RegisterService(&_HopTunnel_serviceDesc, srv)
}

func _HopTunnel_Stream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(HopTunnelServer).Stream(&hopTunnelStreamServer{stream})
}

type HopTunnel_StreamServer interface {
	Send(*HopPacket) error
	Recv() (*HopPacket, error)
	grpc.ServerStream
}

type hopTunnelStreamServer struct {
	grpc.ServerStream
}

func (x *hopTunnelStreamServer) Send(m *HopPacket) error {
	return x.ServerStream.SendMsg(m)
}

func (x *hopTunnelStreamServer) Recv() (*HopPacket, error) {
	m := new(HopPacket)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _HopTunnel_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.HopTunnel",
	HandlerType: (*HopTunnelServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Stream",
			Handler:       _HopTunnel_Stream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/hop_tunnel.proto",
}
